blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='blog_list'),
    path('read/<int:pk>/', ArticleDetailView.as_view(), name='blog_read'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coursach.urls', namespace='coursach')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coursach/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from coursach.apps import CoursachConfig
from coursach.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, \
    MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingDetailView, LetterListView, \
    LetterCreateView, LetterUpdateView, LetterDeleteView, LetterDetailView, client_mailing, stats, HomePageView, \
    turn_off_mailing

app_name = CoursachConfig.name

urlpatterns = [
    path('', cache_page(60)(HomePageView.as_view()), name='home'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('update_client/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('detail_client/<int:pk>/', ClientDetailView.as_view(), name='detail_client'),
    path('mailing/', MailingListView.as_view(), name='mailing'),
    path('create_mailing/', MailingCreateView.as_view(), name='create_mailing'),
    path('update_mailing/<int:pk>/', MailingUpdateView.as_view(), name='update_mailing'),
    path('delete_mailing/<int:pk>/', MailingDeleteView.as_view(), name='delete_mailing'),
    path('detail_mailing/<int:pk>/', MailingDetailView.as_view(), name='detail_mailing'),
    path('letter/', LetterListView.as_view(), name='letter'),
    path('create_letter/', LetterCreateView.as_view(), name='create_letter'),
    path('update_letter/<int:pk>/', LetterUpdateView.as_view(), name='update_letter'),
    path('delete_letter/<int:pk>/', LetterDeleteView.as_view(), name='delete_letter'),
    path('detail_letter/<int:pk>/', LetterDetailView.as_view(), name='detail_letter'),
    path('client_mailing/', client_mailing, name='status'),
    path('stats/', stats, name='stats'),
    path('deactivate_mailing/<int:pk>', turn_off_mailing, name='deactivate')
]

base/models.py
from django.db import models

# Create your models here.

coursach/models.py
from django.conf import settings
from django.db import models
from django.utils.datetime_safe import date


class Client(models.Model):
    NULLABLE = {'blank': True, 'null': True}

    created_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь',
                                     **NULLABLE)
    email = models.EmailField(max_length=250, verbose_name='контактный e-mail')
    full_name = models.CharField(max_length=250, verbose_name='фио')
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)

    def __str__(self):
        return f'{self.full_name}'


class Mailing(models.Model):
    NULLABLE = {'blank': True, 'null': True}

    PERIOD_ONCE_DAY = 'once_a_day'
    PERIOD_ONCE_WEEK = 'once_a_week'
    PERIOD_ONCE_MONTH = 'once_a_month'
    PERIODS = (
        ('once_a_day', 'раз в день'),
        ('once_a_week', 'раз в неделю'),
        ('once_a_month', 'раз в месяц')
    )
    STATUS_COMPLETED = 'completed'
    STATUS_CREATED = 'created'
    STATUS_LAUNCHED = 'launched'
    STATUS_DEACTIVATED = 'deactivated'
    STATUSES = (
        ('completed', 'завершена'),
        ('created', 'создана'),
        ('launched', 'запущена'),
        ('deactivated', 'деактивирована')
    )

    created_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь',
                                     **NULLABLE)
    client = models.ForeignKey('coursach.Client', verbose_name='Клиент', on_delete=models.SET_NULL, null=True)
    message = models.ForeignKey('coursach.Letter', verbose_name='Сообщение', on_delete=models.SET_NULL, null=True)
    time_of_mailing = models.TimeField(verbose_name='Время рассылки', **NULLABLE)
    periodicity = models.CharField(choices=PERIODS, default=PERIOD_ONCE_WEEK, max_length=50,
                                   verbose_name='Периодичность')
    mailing_status = models.CharField(choices=STATUSES, default=STATUS_COMPLETED, max_length=50,
                                      verbose_name='Статус рассылки')
    start_date = models.DateField(default=date.today, verbose_name='Начальная дата')
    end_date = models.DateField(default=date.today, verbose_name='Конечная дата')

    class Meta:
        permissions = [
            ('deactivate',
             'Can deactivate mailing')
        ]


class Letter(models.Model):
    NULLABLE = {'blank': True, 'null': True}

    created_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь',
                                     **NULLABLE)
    letter_topic = models.CharField(max_length=350, verbose_name='Тема письма')
    letter_body = models.TextField(verbose_name='Тело письма')

    def __str__(self):
        return f'{self.letter_topic}'


class MailingTry(models.Model):
    NULLABLE = {'blank': True, 'null': True}

    date = models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')
    status = models.CharField(max_length=50, verbose_name='статус попытки')
    answer = models.CharField(max_length=250, verbose_name='ответ почтового сервера', **NULLABLE)

base/forms.py
from django import forms


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            else:
                field.widget.attrs['class'] = 'form-control'

            field.help_text = ''

coursach/forms.py
from django import forms

from base.forms import StyleFormMixin
from coursach.models import Client, Mailing, Letter


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ['created_user', ]


class MailingForm(StyleFormMixin, forms.ModelForm):
    STATUSES = (
        ('completed', 'завершена'),
        ('created', 'создана'),
        ('launched', 'запущена'),
    )
    mailing_status = forms.ChoiceField(choices=STATUSES, )

    class Meta:
        model = Mailing
        exclude = ['created_user', ]


class LetterForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Letter
        exclude = ['created_user']

base/views.py
from django.shortcuts import render

# Create your views here.

coursach/views.py
import datetime

from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView

from base.services import count_mailing_all, count_mailing_active, count_unique_clients
from coursach.forms import ClientForm, MailingForm, LetterForm
from coursach.models import MailingTry, Client, Mailing, Letter
from blog.models import Article


def stats(request):
    context = {
        'object_list': MailingTry.objects.all()
    }
    return render(request, 'coursach/stats.html', context)


class HomePageView(TemplateView):
    template_name = 'coursach/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['blog'] = Article.objects.all().order_by('?')[:3]
        context_data['count_mailing_all'] = count_mailing_all()
        context_data['count_mailing_active'] = count_mailing_active()
        context_data['count_unique_clients'] = count_unique_clients()
        return context_data


class ClientListView(ListView):
    model = Client

    def get_queryset(self):
        return Client.objects.filter(created_user=self.request.user)


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('coursach:client_list')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.created_user = self.request.user
            self.object.save()
        return super().form_valid(form)


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('coursach:client_list')

    def get_queryset(self):
        return Client.objects.filter(created_user=self.request.user)


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('coursach:client_list')

    def get_queryset(self):
        return Client.objects.filter(created_user=self.request.user)


class ClientDetailView(DetailView):
    model = Client

    def get_queryset(self):
        return Client.objects.filter(user_create=self.request.user)


class MailingListView(ListView):
    model = Mailing

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('coursach.view_mailing'):
            return queryset

        return queryset.filter(created_user=self.request.user)


class MailingCreateView(CreateView):
    model = Mailing
    fields = '__all__'
    success_url = reverse_lazy('coursach:mailing')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.created_user = self.request.user
            self.object.save()
        return super().form_valid(form)


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('coursach:mailing')

    def get_queryset(self):
        return Mailing.objects.filter(created_user=self.request.user)


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('coursach:mailing')

    def get_queryset(self):
        return Mailing.objects.filter(created_user=self.request.user)


class MailingDetailView(DetailView):
    model = Mailing

    def get_queryset(self):
        return Mailing.objects.filter(created_user=self.request.user)


class LetterListView(ListView):
    model = Letter

    def get_queryset(self):
        return Letter.objects.filter(created_user=self.request.user)


class LetterCreateView(CreateView):
    model = Letter
    form_class = LetterForm
    success_url = reverse_lazy('coursach:letter')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.created_user = self.request.user
            self.object.save()
        return super().form_valid(form)


class LetterUpdateView(UpdateView):
    model = Letter
    form_class = LetterForm
    success_url = reverse_lazy('coursach:letter')

    def get_queryset(self):
        return Letter.objects.filter(created_user=self.request.user)


class LetterDeleteView(DeleteView):
    model = Letter
    success_url = reverse_lazy('coursach:letter')

    def get_queryset(self):
        return Letter.objects.filter(created_user=self.request.user)


class LetterDetailView(DetailView):
    model = Letter

    def get_queryset(self):
        return Letter.objects.filter(created_user=self.request.user)


def client_mailing(request):
    mailing_items = Mailing.objects.all()
    for item in mailing_items:
        if (
                item.mailing_status == Mailing.STATUS_CREATED or item.mailing_status == Mailing.STATUS_LAUNCHED) and item.start_date == datetime.date.today() and item.end_date >= datetime.date.today() and item.time_of_mailing >= datetime.datetime.now().time():
            item.mailing_status = Mailing.STATUS_LAUNCHED
            item.save()
            try:
                result = send_mail(
                    subject=item.message.letter_topic,
                    message=item.message.letter_body,
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[item.client.email],
                    fail_silently=False
                )

                if result:
                    item.mailing_status = Mailing.STATUS_COMPLETED
                    item.save()
                MailingTry.objects.create(
                    status=item.mailing_status,
                    answer=200
                )
            except Exception as e:
                MailingTry.objects.create(
                    status=item.mailing_status,
                    answer=e
                )
    return redirect(reverse('coursach:mailing'))


@permission_required('coursach.turn_off')
def turn_off_mailing(request, pk):
    current_mailing = get_object_or_404(Mailing, pk=pk)
    if current_mailing:
        current_mailing.state_mail = Mailing.STATUS_DEACTIVATED
        current_mailing.save()
    return redirect(request.META.get('HTTP_REFERER'))


def mail_customer_confirm(request):
    id = request.user.id
    client_mailing(id)
    return redirect(reverse('coursach:mailing'))

coursach/templates/coursach/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Сервис управления рассылками</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
{% include 'coursach/includes/main_menu.html' %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

coursach/templates/coursach/client_confirm_delete.html
{% extends 'coursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <a href="{% url 'coursach:coursach' %}">Отмена</a>
                        <button type="submit">Удалить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

coursach/templates/coursach/client_detail.html
{% extends 'coursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Контактный email</td>
                            <td>{{ object.email }}</td>
                        </tr>
                        <tr>
                            <td>ФИО</td>
                            <td>{{ object.full_name }}</td>
                        </tr>
                        <tr>
                            <td>Комментарии</td>
                            <td>{{ object.comment }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

coursach/templates/coursach/client_form.html
{% extends 'coursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

coursach/templates/coursach/client_list.html
{% extends 'coursach/base.html' %}

{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primery border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Сервис</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-info" href="{% url 'coursach:create_client' %}">Создать клиента</a>
    </nav>
</div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Email</th>
            <th scope="col">ФИО</th>
            <th scope="col">Комментарий</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <td>
                    <a href="{% url 'coursach:detail_client' object.pk %}">
                        #{{ object.pk }}
                    </a>
                </td>
                <td>{{ object.email }}</td>
                <td>{{ object.full_name }}</td>
                <td>{{ object.comment }}</td>
                <td>
                    <a class="btn btn-info" href="{% url 'coursach:update_client' object.pk %}">Update</a>
                    <a class="btn btn-danger" href="{% url 'coursach:delete_client' object.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

coursach/templates/coursach/home.html
{% extends 'coursach/base.html' %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col-12">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Наша статистика</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Всего рассылок : {{count_mailing_all}}</li>
                    <li>Активных рассылок всего : {{count_mailing_active}}</li>
                    <li>Количество уникальных клиентов для рассылок : {{count_unique_clients}}</li>
                </ul>
                <a class="p-2 btn btn-outline-primary"
                   href="{% url 'coursach:client_list' %}">Перейти в приложение</a>
            </div>
        </div>
    </div>
</div>

<h2 class="display-6 text-center mb-4">Последние статьи</h2>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-dark-emphasis">{{ object.title }}</strong>
                <h3 class="mb-0">{{ object.title }}</h3>
                <div class="mb-1 text-muted">{{ item.created_at|date:"d M" }}</div>
                <p class="card-text mb-auto">{{ item.body|slice:150 }}...</p>
                <a href="{% url 'blog:blog_read' object.pk %}" class="stretched-link text-dark-emphasis">Continue reading</a>
            </div>
            <div class="col-auto d-none d-lg-block">
                <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg"
                     role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                     focusable="false"><title>Placeholder</title>
                    <img src="/media/{{ object.image }}" alt="" border=3 height=250 width=450>
                    <text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
                </svg>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

coursach/templates/coursach/letter_confirm_delete.html
{% extends 'coursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <a href="{% url 'coursach:coursach' %}">Отмена</a>
                        <button type="submit">Удалить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

coursach/templates/coursach/letter_detail.html
{% extends 'coursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Тема письма</td>
                            <td>{{ object.letter_topic }}</td>
                        </tr>
                        <tr>
                            <td>Тело пиcьма</td>
                            <td>{{ object.letter_body }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

coursach/templates/coursach/letter_form.html
{% extends 'coursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

coursach/templates/coursach/letter_list.html
{% extends 'coursach/base.html' %}

{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primery border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Сервис</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-info" href="{% url 'coursach:create_letter' %}">Создать письмо</a>
    </nav>
</div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Тема письма</th>
            <th scope="col">Тело письма</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <td>
                    <a href="{% url 'coursach:detail_letter' object.pk %}">
                        #{{ object.pk }}
                    </a>
                </td>
                <td>{{ object.letter_topic }}</td>
                <td>{{ object.letter_body }}</td>
                <td>
                    <a class="btn btn-info" href="{% url 'coursach:update_letter' object.pk %}">Update</a>
                    <a class="btn btn-danger" href="{% url 'coursach:delete_letter' object.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

coursach/templates/coursach/mailing_detail.html
{% extends 'coursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Клиент</td>
                            <td>{{ object.client.email }}</td>
                        </tr>
                        <tr>
                            <td>Начальная дата</td>
                            <td>{{ object.start_date }}</td>
                        </tr>
                        <tr>
                            <td>Конечная дата</td>
                            <td>{{ object.end_date }}</td>
                        </tr>
                        <tr>
                            <td>Время отправки</td>
                            <td>{{ object.time_of_mailing }}</td>
                        </tr>
                        <tr>
                            <td>Периодичность</td>
                            <td>{{ object.periodicity }}</td>
                        </tr>
                        <tr>
                            <td>Периодичность</td>
                            <td>{{ object.mailing_status }}</td>
                        </tr>
                        <tr>
                            <td>Тема письма</td>
                            <td>{{ object.message.letter_topic }}</td>
                        </tr>
                        <tr>
                            <td>Тело письма</td>
                            <td>{{ object.message.letter_body }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

coursach/templates/coursach/mailing_form.html
{% extends 'coursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

coursach/templates/coursach/mailing_list.html
{% extends 'coursach/base.html' %}

{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primery border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Сервис</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-info" href="{% url 'coursach:create_mailing' %}">Создать рассылку</a>
        <a class="btn btn-info" href="{% url 'coursach:status' %}">Статус отправки</a>
    </nav>
</div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Клиент</th>
            <th scope="col">Начальная дата</th>
            <th scope="col">Конечная дата</th>
            <th scope="col">Время рассылки</th>
            <th scope="col">Периодичность</th>
            <th scope="col">Статус рассылки</th>
            <th scope="col">Тема письма</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <td>
                    <a href="{% url 'coursach:detail_mailing' object.pk %}">
                        #{{ object.pk }}
                    </a>
                </td>
                <td>{{ object.client.email }}</td>
                <td>{{ object.start_date }}</td>
                <td>{{ object.end_date }}</td>
                <td>{{ object.time_of_mailing }}</td>
                <td>{{ object.periodicity }}</td>
                <td>{{ object.mailing_status }}</td>
                <td>{{ object.message.letter_topic}}</td>
                <td>
                    <a class="btn btn-info" href="{% url 'coursach:update_mailing' object.pk %}">Update</a>
                    <a class="btn btn-danger" href="{% url 'coursach:delete_mailing' object.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

coursach/templates/coursach/stats.html
{% extends 'coursach/base.html' %}

{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primery border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Сервис</h5>
</div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Дата и время попытки</th>
            <th scope="col">Статус попытки</th>
            <th scope="col">Ответ почтового сервера</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <td>{{ object.id }}</td>
                <td>{{ object.date }}</td>
                <td>{{ object.status }}</td>
                <td>{{ object.answer }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}