blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='blog_list'),
    path('read/<int:pk>/', ArticleDetailView.as_view(), name='blog_read'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coursach.urls', namespace='coursach')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coursach/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from coursach.apps import CoursachConfig
from coursach.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, \
    MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingDetailView, LetterListView, \
    LetterCreateView, LetterUpdateView, LetterDeleteView, LetterDetailView, client_mailing, stats, HomePageView, \
    turn_off_mailing

app_name = CoursachConfig.name

urlpatterns = [
    path('', cache_page(60)(HomePageView.as_view()), name='home'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('update_client/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('detail_client/<int:pk>/', ClientDetailView.as_view(), name='detail_client'),
    path('mailing/', MailingListView.as_view(), name='mailing'),
    path('create_mailing/', MailingCreateView.as_view(), name='create_mailing'),
    path('update_mailing/<int:pk>/', MailingUpdateView.as_view(), name='update_mailing'),
    path('delete_mailing/<int:pk>/', MailingDeleteView.as_view(), name='delete_mailing'),
    path('detail_mailing/<int:pk>/', MailingDetailView.as_view(), name='detail_mailing'),
    path('letter/', LetterListView.as_view(), name='letter'),
    path('create_letter/', LetterCreateView.as_view(), name='create_letter'),
    path('update_letter/<int:pk>/', LetterUpdateView.as_view(), name='update_letter'),
    path('delete_letter/<int:pk>/', LetterDeleteView.as_view(), name='delete_letter'),
    path('detail_letter/<int:pk>/', LetterDetailView.as_view(), name='detail_letter'),
    path('client_mailing/', client_mailing, name='status'),
    path('stats/', stats, name='stats'),
    path('deactivate_mailing/<int:pk>', turn_off_mailing, name='deactivate')
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import SigninView, SignupView, SignupSuccessView, CustomPasswordResetView, \
    CustomPasswordResetConfirmView, CustomPasswordResetDoneView, CustomPasswordResetCompleteView, verify_email, \
    simple_reset_password, UserEditProfileView, user_status_change

app_name = UsersConfig.name

urlpatterns = [
    path('', SigninView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', SignupView.as_view(), name='register'),
    path('register/success/', SignupSuccessView.as_view(), name='register_success'),
    path('password/reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/<uidb64>/confirm/<token>/', CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('verify/<str:token>/', verify_email, name='verify_email'),
    path('simple/reset/', simple_reset_password, name='simple_reset'),
    path('profile/', UserEditProfileView.as_view(), name='profile'),
    path('user_change/<int:pk>/', user_status_change, name='user_change')
]

base/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class CustomUserManager(UserManager):
    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user


class User(AbstractUser):
    objects = CustomUserManager()

    username = None
    verify_token = models.CharField(max_length=50, verbose_name='токен верификации', **NULLABLE)
    verify_token_expired = models.DateTimeField(**NULLABLE, verbose_name='дата истечения токена')
    email = models.EmailField(verbose_name='Почта', unique=True)
    new_password = models.CharField(verbose_name='новый пароль', max_length=128, **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [
            (
                'change_status',
                'Can change is_staff'
            )
        ]

base/forms.py
from django import forms


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            else:
                field.widget.attrs['class'] = 'form-control'

            field.help_text = ''

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UsernameField, PasswordResetForm, \
    UserChangeForm

from base.forms import StyleFormMixin
from users.models import User


class CustomEditUserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email',)


class SigninForm(StyleFormMixin, AuthenticationForm):
    pass


class SignupForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email',)
        field_classes = {"username": UsernameField}


class CustomPasswordResetForm(StyleFormMixin, PasswordResetForm):
    pass

base/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from datetime import datetime

import pytz
from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from users.forms import SigninForm, SignupForm, CustomPasswordResetForm, CustomEditUserForm
from users.models import User
from users.services import set_verify_token_and_send_mail, generate_password_and_end_mail


class UserEditProfileView(UpdateView):
    model = User
    template_name = 'users/profile.html'
    form_class = CustomEditUserForm
    success_url = reverse_lazy('coursach:home')

    def get_object(self, queryset=None):
        return self.request.user


class SigninView(LoginView):
    template_name = 'users/login.html'
    form_class = SigninForm


class SignupView(CreateView):
    template_name = 'users/register.html'
    model = User
    form_class = SignupForm
    success_url = reverse_lazy('users:register_success')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save()
            set_verify_token_and_send_mail(self.object)
        return super().form_valid(form)


class SignupSuccessView(TemplateView):
    template_name = 'users/signup_success.html'


class VerifySuccessView(TemplateView):
    template_name = 'users/verify_success.html'


def verify_email(request, token):
    current_user = User.objects.filter(verify_token=token).first()
    if current_user:
        now = datetime.now(pytz.timezone(settings.TIME_ZONE))
        if now > current_user.verify_token_expired:
            current_user.delete()
            return render(request, 'users/verify_token_expired.html')

        current_user.is_active = True
        current_user.verify_token = None
        current_user.verify_token_expired = None
        current_user.save()
        return redirect('users:login')

    return render(request, 'users/verify_failed.html')


class CustomPasswordResetView(PasswordResetView):
    template_name = 'users/password_reset_form.html'
    form_class = CustomPasswordResetForm
    success_url = reverse_lazy('users:password_reset_done')
    email_template_name = 'users/email_reset.html'
    from_email = settings.EMAIL_HOST_USER


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/reset_done.html'


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/reset_complete.html'


def simple_reset_password(request):
    if request.method == 'POST':
        current_user = User.objects.filter(email=request.POST.get('email')).first()
        if current_user:
            generate_password_and_end_mail(current_user)
    return render(request, 'users/simple_reset.html')


def confirm_new_generated_password(request):
    current_user = User.objects.filter(email=request.GET.get('email')).first()
    current_user.password = current_user.new_password
    current_user.new_password = None
    current_user.save()
    return redirect(...)


@permission_required('users.change_status')
def user_status_change(request, pk):
    current_user = get_object_or_404(User, pk=pk)
    if current_user.is_superuser:
        return HttpResponseForbidden()
    if current_user.is_active:
        current_user.is_active = False
    else:
        current_user.is_active = True
    current_user.save()

    return redirect(request.META.get('HTTP_REFERER'))

users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Signin Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/sign-in/">


    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        html,
        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            max-width: 330px;
            padding: 15px;
        }

        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>

</head>
<body class="text-center">

<main class="form-signin w-100 m-auto">
    <h1>Сервис управления рассылкой</h1>
    {% block content %}
    {% endblock %}
    <p class="mt-5 mb-3 text-muted">&copy; 2023–{% now 'Y' %}</p>
</main>


</body>
</html>

users/templates/users/email_reset.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Авторизуйтесь</h1>
    {{ form.as_p }}
    <button class="w-100 btn btn-lg btn-primary" type="submit">Вход</button>
    <a class="btn btn-link" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
    <br>
    <a class="btn btn-link" href="{% url 'users:register'%}">Нет аккаунта?</a>
</form>
{% endblock %}

users/templates/users/profile.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Сохранить</button>
            </form>
        </div>
    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Зарегистрируйтесь</h1>
    {{ form.as_p }}
    {% csrf_token %}
    <button class="w-100 btn btn-lg btn-primary" type="submit">Регистрация</button>
    <a class="btn btn-link" href="{% url 'users:login' %}">Есть аккаунт?</a>
</form>

{% endblock %}

users/templates/users/reset_complete.html
{% extends 'users/base.html' %}

{% block content %}

<p>
    И снова поздравляем! Теперь можно пользоваться сервисом
</p>
<a href="{% url 'users:login' %}" class="btn btn-link">
    На главную
</a>

{% endblock %}

users/templates/users/reset_confirm.html
{% extends 'users/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Введите новый пароль</h1>
    {{ form.as_p }}
    <button class="w-100 btn btn-lg btn-primary" type="submit">Изменить пароль</button>
</form>
{% endblock %}

users/templates/users/reset_done.html
{% extends 'users/base.html' %}

{% block content %}

    <p>
        Иди на почту и проверяй ссылку
    </p>
    <a href="{% url 'users:login' %}" class="btn btn-link">
        На главную
    </a>

{% endblock %}

users/templates/users/signup_success.html
{% extends 'users/base.html' %}

{% block content %}

    <p>
    Поздравляем! Вы зарегестрировались на сервисе рассылки.
    </p>
    <p>
    Пожалуйста, чтобы пользоваться сервисом, проверьте почту и перейдите по ссылке из письма от нас
    </p>
    <a href="{% url 'users:login' %}" class="btn btn-link">
        Потом загляну на почту
    </a>

{% endblock %}

users/templates/users/simple_reset.html
{% extends 'users/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <h1 class="h3 mb-3 fw-normal">Сброс пароля</h1>
        <input class="form-control" name="email" type="email" />
        <button class="w-100 btn btn-lg btn-primary" type="submit">Сброс пароля</button>
        <br>
        <a class="btn btn-link" href="{% url 'users:login' %}">Передумал</a>
    </form>
{% endblock %}

users/templates/users/verify_failed.html
{% extends 'users/base.html' %}

{% block content %}

    <p>
        Поражены вашей неудачей :(
    </p>
    <a href="{% url 'users:login' %}" class="btn btn-link">
        На главную
    </a> или
    <a href="{% url 'users:register' %}" class="btn btn-link">
        Попробовать еще раз
    </a>
    ну или
    <a href="mailto:support@service.com">Напишите в саппорт</a>

{% endblock %}

users/templates/users/verify_success.html
{% extends 'users/base.html' %}

{% block content %}

    <p>
        И снова поздравляем! Теперь можно пользоваться сервисом
    </p>
    <a href="{% url 'users:login' %}" class="btn btn-link">
        На главную
    </a>

{% endblock %}

users/templates/users/verify_token_expired.html
{% extends 'users/base.html' %}

{% block content %}

    <p>
        Токен не дождался :(
    </p>
    <p>
    Мы удалили пользователя, можете пробовать еще раз
    </p>
    <a href="{% url 'coursach:home' %}" class="btn btn-link">
        На главную
    </a> или
    <a href="{% url 'users:register' %}" class="btn btn-link">
        Попробовать еще раз
    </a>
{% endblock %}

users/templates/users/verify_token_success.html
{% extends 'users/base.html' %}

{% block content %}

<p>
    Ура! Все получилось!
</p>
<a href="{% url 'coursach:home' %}" class="btn btn-link">
    На главную
</a> или
{% endblock %}